version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: 'true'
      SERVER_PORT: 25566
      MEMORY: ''
      ENABLE_WHITELIST: 'true'
      TZ: '/etc/localtime:/etc/localtime:ro'
      ENABLE_ROLLING_LOGS: 'true'
      LOG_TIMESTAMP: 'true'
      RCON_PASSWORD: 'REDACTED'
    ports:
      - "25566:25566"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}
